---
name: Update JP
on:
  workflow_dispatch: null

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Installing requirements
        run: |
          pip install -r requirements.txt
      - name: Fetching data
        run: |
          python ./py/jp/main.py --download-all
      - name: Create Commit
        run: |
          git add .
          git config --global user.email "bot@github.com"
          git config --global user.name "Github Bot"
          git commit -m "[Update] $(date +%Y-%m-%d-%H-%M-%S)"
      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: production
